AllCops:
  Exclude:
    - db/*.rb
    - db/migrate/*.rb
    - node_modules/**/*
    - spec/features/user/user_sees_bookmarks_on_dashboard_spec.rb
    - config/routes.rb
    - bin/setup
    - bin/update
    - spec/rails_helper.rb

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

inherit_from: .rubocop_todo.yml
